### ISSUE TITLE
Error in running tanner

### ISSUE THREAD

**Issue by mzfr** [mushorg/tanner#240] opened 2018-03-26 16:12 UTC
Until yesterday everything was working fine but not whenever I do `sudo tanner` I am getting the following error:
```
Traceback (most recent call last):
  File "/usr/local/bin/tanner", line 4, in <module>
    __import__('pkg_resources').require('Tanner==0.5.0')
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'Tanner==0.5.0' distribution was not found and is required by the application
```

**Comment by afeena** [comment] 2018-03-26 16:56
Right now I can't reproduce your problem
I deleted all installed tanner, download master branch and then install again. It works ok.

Could you please describe a bit more:
Have you run master branch? Do you have any changes which can affect run? Which OS do you use? pip version?

**Comment by mzfr** [comment] 2018-03-26 17:17
I haven't made any changes to my master branch.
I even tried `git pull` to see if there was any changes required but it showed `Already up to date`.
I use KDE. pip version is 9.0.1

**Comment by mzfr** [comment] 2018-03-27 13:20
@afeena  I tried but could not get it working so I took the easy way out and deleted installed tanner and downloaded the master branch and then install it again.

Should I close this issue or should I keep it open if someone would like to investigate the issue ?

**Comment by afeena** [comment] 2018-03-28 22:07
@mzfr since installation with master works well, I think we can close it. It can be very host-specific issue. In any case - we can open new one :)

**Closed** 2018-03-28 22:07 UTC
